blank_issues_enabled: false
contact_links:
  - name: "\U0001F6E1 Report a security vulnerability"
    about: Please refer to the SECURITY.md file for instructions.
    url: ./../../SECURITY.md
  - name: "\U0001F6F1 Request support"
    about: You can start a discussion.
    url: https://github.com/STMicroelectronics/STM32CubeU5-V2-Preview/discussions
